### ISSUE TITLE
Dataset link unavailable

### ISSUE THREAD

**Issue by Ab-Tx** [ziv-lin/r3live_dataset#7]
Hello, the Microsoft OneDrive link for the datasets is currently not working.

**Comment by ziv-lin** [comment]
Hi, I have just moved the old bag to a new account now, could you please check if is following link can be accessed normally?
https://1drv.ms/f/c/3e715b7aa136191a/EqpK7QnN4OpCqHmL2ykpZ50Bjz3pyJ0kwyvwpBBLtzR4bQ?e=TqPN8E

**Comment by Ab-Tx** [comment]
Yes, it can. 
Thank you very much.
